name: Update Manifests

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Update the manifest file
    - name: Update Manifests
      run: |
        sed -i 's/replicas: .*/replicas: 4/' manifests/deployment.yaml

    # Commit and push the changes
    - name: Commit and Push Changes
      run: |
        git config --global user.name "Batnini "
        git config --global user.email "batniniabdelkader@yahoo.com"
        git add manifests/deployment.yaml
        git commit -m "Automated update: Set replicas to 4"
        git push origin main
